// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kontent.Ai.Delivery.Abstractions;

namespace Kontent.Ai.Boilerplate.Models.ContentTypes
{
    public partial class Blog
    {
        public const string Codename = "blog";
        public const string IsFeaturedCodename = "is_featured";
        public const string LinkedAuthorCodename = "linked_author";
        public const string TextCodename = "text";
        public const string TitleCodename = "title";

        public IEnumerable<IMultipleChoiceOption> IsFeatured { get; set; }
        public IEnumerable<object> LinkedAuthor { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Text { get; set; }
        public string Title { get; set; }
    }
}